---
- name: Server Patch Compliance Check and Report
  hosts: all
  gather_facts: yes
  become: true

  vars:
    local_json_dir: "/tmp/compliance_json"

  tasks:
    - name: Ensure local JSON directory exists
      delegate_to: localhost
      become: false
      file:
        path: "{{ local_json_dir }}"
        state: directory
        mode: '0755'

    - name: Get patch compliance status
      shell: "cat /etc/ansible/fact.d/site.fact | grep patchcompliance || echo 'patchcompliance: unknown'"
      register: compliance_raw
      ignore_errors: yes

    - name: Get server IP
      shell: hostname -I | awk '{print $1}'
      register: ip_raw

    - name: Get uptime
      command: uptime -p
      register: uptime_raw

    - name: Build compliance data
      set_fact:
        compliance_info:
          server_ip: "{{ ip_raw.stdout }}"
          server_name: "{{ ansible_hostname }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
          kernel_version: "{{ ansible_kernel }}"
          uptime: "{{ uptime_raw.stdout }}"
          compliance_status: "{{ (compliance_raw.stdout | regex_search('patchcompliance:\\s*(\\S+)', '\\1')) | default('unknown') }}"

    - name: Write data to local JSON file
      delegate_to: localhost
      become: false
      copy:
        content: "{{ compliance_info | to_nice_json }}"
        dest: "{{ local_json_dir }}/{{ inventory_hostname }}.json"
